"""Document ingestion pipeline tests."""

import pytest

from app.models.document import DocumentChunk, DocumentVersion

SOP_TEXT = b"""CLIENT REGISTRATION SOP
Version 3.2

1. PURPOSE
This procedure describes how staff must register a new client at the facility.

2. REGISTRATION PROCEDURE
2.1 Every new client must present a valid government-issued identification document.
2.2 The registration officer must capture the client's full name, date of birth and sex.
2.3 A unique client identification number must be generated by the system.

3. DATA PROTECTION
3.1 Client records are confidential and may only be accessed by authorised staff.
"""


def upload(client, headers, filename="sop.txt", content=SOP_TEXT, **extra):
    data = {"title": "Client Registration SOP", "department": "Clinical Services", "version_label": "3.2"}
    data.update(extra)
    return client.post(
        "/api/v1/documents/upload",
        headers=headers,
        files={"file": (filename, content, "text/plain")},
        data=data,
    )


def test_upload_extracts_chunks_and_marks_ready(client, admin, db):
    response = upload(client, admin["headers"])
    assert response.status_code == 201, response.text

    body = response.json()
    assert body["status"] == "Active"
    assert body["active_version_label"] == "3.2"

    version = body["versions"][0]
    assert version["processing_status"] == "ready"
    assert version["processing_error"] is None
    assert version["chunk_count"] > 0

    chunks = db.query(DocumentChunk).filter_by(document_version_id=version["id"]).all()
    assert len(chunks) == version["chunk_count"]
    assert all(c.embedding is not None for c in chunks)
    assert all(c.chunk_index is not None for c in chunks)
    # Section metadata should not be empty when headings are detectable.
    assert any(c.section for c in chunks)


def test_upload_rejects_unsupported_file_type(client, admin):
    response = upload(client, admin["headers"], filename="bad.exe", content=b"MZ")
    assert response.status_code == 400
    assert "Unsupported file type" in response.json()["detail"]


def test_upload_rejects_empty_file(client, admin):
    response = upload(client, admin["headers"], content=b"")
    assert response.status_code == 400


def test_new_version_becomes_exclusively_active(client, admin, db):
    first = upload(client, admin["headers"]).json()
    document_id = first["id"]

    response = client.post(
        f"/api/v1/documents/{document_id}/versions",
        headers=admin["headers"],
        files={"file": ("v2.txt", SOP_TEXT + b"\n4. REVISION\nUpdated step.", "text/plain")},
        data={"version_label": "4.0", "activate": "true"},
    )
    assert response.status_code == 200, response.text
    assert response.json()["processing_status"] == "ready"

    versions = db.query(DocumentVersion).filter_by(document_id=document_id).all()
    assert len(versions) == 2
    active = [v for v in versions if v.is_active]
    assert len(active) == 1
    assert active[0].version_label == "4.0"


def test_activating_a_version_deactivates_siblings(client, admin, db):
    first = upload(client, admin["headers"]).json()
    document_id = first["id"]
    original_version_id = first["versions"][0]["id"]

    client.post(
        f"/api/v1/documents/{document_id}/versions",
        headers=admin["headers"],
        files={"file": ("v2.txt", SOP_TEXT, "text/plain")},
        data={"version_label": "4.0", "activate": "true"},
    )

    response = client.post(
        f"/api/v1/documents/{document_id}/versions/{original_version_id}/activate",
        headers=admin["headers"],
    )
    assert response.status_code == 200

    versions = db.query(DocumentVersion).filter_by(document_id=document_id).all()
    assert sum(1 for v in versions if v.is_active) == 1
    assert (
        db.query(DocumentVersion).filter_by(id=original_version_id).one().is_active is True
    )


def test_reprocess_document(client, admin):
    document_id = upload(client, admin["headers"]).json()["id"]
    response = client.post(f"/api/v1/documents/{document_id}/reprocess", headers=admin["headers"])
    assert response.status_code == 200
    assert response.json()["processing_status"] == "ready"
    assert response.json()["chunk_count"] > 0


def test_delete_document_removes_versions_and_chunks(client, admin, db):
    document_id = upload(client, admin["headers"]).json()["id"]
    assert client.delete(f"/api/v1/documents/{document_id}", headers=admin["headers"]).status_code == 204
    assert db.query(DocumentVersion).filter_by(document_id=document_id).count() == 0
    assert db.query(DocumentChunk).filter_by(document_id=document_id).count() == 0


def test_normal_user_only_sees_active_documents(client, admin, normal_user):
    upload(client, admin["headers"])
    response = client.get("/api/v1/documents/", headers=normal_user["headers"])
    assert response.status_code == 200
    assert all(doc["status"] == "Active" for doc in response.json())


# --------------------------------------------- citation "view source" endpoint
def test_chunk_source_endpoint_returns_content(client, admin, db):
    body = upload(client, admin["headers"]).json()
    chunk = db.query(DocumentChunk).filter_by(document_id=body["id"]).first()

    response = client.get(f"/api/v1/documents/chunks/{chunk.id}", headers=admin["headers"])
    assert response.status_code == 200
    payload = response.json()
    assert payload["chunk_id"] == chunk.id
    assert payload["document_title"] == "Client Registration SOP"
    assert payload["content"] == chunk.content


def test_chunk_source_endpoint_404s_for_missing_chunk(client, admin):
    assert client.get("/api/v1/documents/chunks/99999", headers=admin["headers"]).status_code == 404


def test_chunk_source_requires_authentication(client):
    assert client.get("/api/v1/documents/chunks/1").status_code == 401


# ------------------------------------------------------- embedding service unit
def test_embedding_dimension_mismatch_is_detected():
    from app.rag.embeddings import EmbeddingError, EmbeddingService

    class BadProvider:
        name = "bad"
        embed_model = "bad-model"
        embedding_dim = 1024

        def embed(self, text):
            return [0.0] * 768

    service = EmbeddingService(provider=BadProvider())
    with pytest.raises(EmbeddingError):
        service.embed("hello world")


def test_embedding_service_reports_dimension():
    from app.rag.embeddings import get_embedding_service

    assert get_embedding_service().dimension == 1024


def test_embedding_rejects_empty_text():
    from app.rag.embeddings import EmbeddingError, get_embedding_service

    with pytest.raises(EmbeddingError):
        get_embedding_service().embed("   ")
